project:
  type: website

website:
  title: "shinylive-quarto-test"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: app-ex1.qmd
        text: "App 1"
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

filters:
  - shinylive


